# packages in environment at /home/alex/anaconda3/envs/sat:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
affine                    2.3.0                      py_0  
astroid                   2.4.2                    pypi_0    pypi
async_generator           1.10             py37h28b3542_0  
attrs                     20.2.0                     py_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.10.14                    0  
cairo                     1.14.12              h8948797_3  
certifi                   2020.6.20          pyhd3eb1b0_3  
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                      py_0  
click-plugins             1.1.1                      py_0  
cligj                     0.7.0            py37h06a4308_0  
cloudpickle               1.6.0                      py_0  
curl                      7.67.0               hbc83047_0  
cycler                    0.10.0                   py37_0  
cytoolz                   0.11.0           py37h7b6447c_0  
dask-core                 2.30.0                     py_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
expat                     2.2.10               he6710b0_2  
fiona                     1.8.4            py37hc38cc03_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
freexl                    1.0.5                h14c3975_0  
gdal                      2.3.3            py37hbb2a789_0  
geojson                   2.5.0                    pypi_0    pypi
geomet                    0.2.1.post1              pypi_0    pypi
geopandas                 0.6.1                      py_0  
geos                      3.7.1                he6710b0_0  
giflib                    5.1.4                h14c3975_1  
glib                      2.63.1               h5a9c865_0  
greenlet                  0.4.17                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.4               hb1b8bf9_0  
html2text                 2020.1.16                pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.19.0           py37hb070fc8_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_1  
isort                     5.6.4                    pypi_0    pypi
jedi                      0.17.2                   py37_0  
jinja2                    2.11.2                     py_0  
joblib                    0.17.0                     py_0  
jpeg                      9b                   h024ee3a_2  
json-c                    0.13.1               h1bed415_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab_pygments       0.1.2                      py_0  
kealib                    1.4.7                hd0c454d_6  
kiwisolver                1.3.0            py37h2531618_0  
krb5                      1.16.4               h173b8e3_0  
lazy-object-proxy         1.4.3                    pypi_0    pypi
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libboost                  1.67.0               h46d08c1_4  
libcurl                   7.67.0               h20c2e04_0  
libdap4                   3.19.1               h6ec2957_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   2.3.3                h2e7e64b_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libkml                    1.3.0                h590aaf7_4  
libnetcdf                 4.6.1                h11d0813_2  
libpng                    1.6.37               hbc83047_0  
libpq                     11.2                 h20c2e04_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libspatialite             4.3.0a              hb08deb6_19  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
markupsafe                1.1.1            py37h14c3975_1  
matplotlib-base           3.3.2            py37h817c723_0  
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
msgpack                   1.0.0                    pypi_0    pypi
munch                     2.5.0                      py_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
neovim                    0.3.1                    pypi_0    pypi
nest-asyncio              1.4.1                      py_0  
networkx                  2.5                        py_0  
notebook                  6.0.3                    py37_0  
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46                     py37_0  
openjpeg                  2.3.0                h05c96fa_1  
openssl                   1.1.1h               h7b6447c_0  
packaging                 20.4                       py_0  
pandas                    1.1.3            py37he6710b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.2                    py37_1  
parso                     0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pep8                      1.7.1                    pypi_0    pypi
pexpect                   4.8.0                    py37_1  
pickleshare               0.7.5                 py37_1001  
pillow                    8.0.1            py37he98fc37_0  
pip                       20.2.4           py37h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
poppler                   0.65.0               h581218d_1  
poppler-data              0.4.10               h06a4308_0  
proj4                     5.2.0                he6710b0_1  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
ptyprocess                0.6.0                    py37_0  
pygments                  2.7.2              pyhd3eb1b0_0  
pylint                    2.6.0                    pypi_0    pypi
pynvim                    0.4.2                    pypi_0    pypi
pyparsing                 2.4.7                      py_0  
pyproj                    1.9.6            py37h14380d9_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.17.3           py37h7b6447c_0  
python                    3.7.7           h191fe78_0_cpython  
python-dateutil           2.8.1                      py_0  
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py37h7b6447c_2  
pyyaml                    5.3.1            py37h7b6447c_1  
pyzmq                     19.0.2           py37he6710b0_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
rasterio                  1.0.21           py37hc38cc03_0  
readline                  7.0                  h7b6447c_5  
requests                  2.24.0                   pypi_0    pypi
rtree                     0.9.4                    py37_1  
scikit-image              0.17.2           py37hdf5156a_0  
scikit-learn              0.23.2           py37h0573a6f_0  
scipy                     1.5.2            py37h0b6359f_0  
send2trash                1.5.0                    py37_0  
sentinelsat               0.14                     pypi_0    pypi
setuptools                50.3.0           py37h06a4308_1  
shapely                   1.6.4            py37h86c5351_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0                     py_0  
snuggs                    1.4.7                      py_0  
sqlite                    3.33.0               h62c20be_0  
terminado                 0.9.1                    py37_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2020.10.1        py37hdd07704_2  
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                     py_0  
tornado                   6.0.4            py37h7b6447c_1  
tqdm                      4.51.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0  
typed-ast                 1.4.1                    pypi_0    pypi
urllib3                   1.25.11                  pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1                   pypi_0    pypi
xerces-c                  3.2.3                h780794e_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
